// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "server/00-include.hpp"
#include "server/api.hpp"
#include "server/var.hpp"
#endif // __cplusplus
