// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "asm/asm.h"
#include "asm/cpuid.h"
#include "asm/cr.h"
#include "asm/flags.h"
#include "asm/io.h"
#include "asm/mem.h"
#include "asm/msr.h"
#include "asm/reg.h"
#include "asm/syscall.h"
#ifdef __cplusplus
}
#endif // __cplusplus
