// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "type/00-include.hpp"
#include "type/type.hpp"
#include "type/type_traits.hpp"
#endif // __cplusplus
