//| ============================================================================================================== |
//| Copyright (c) 2025 plos-clan                                                                                   |
//|                                                                                                                |
//| This file is part of the Pico Logic OS.                                                                        |
//|                                                                                                                |
//| Licensed under either of:                                                                                      |
//| - Apache License, Version 2.0 (see LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0)               |
//| - MIT License (see LICENSE-MIT or https://opensource.org/licenses/MIT)                                         |
//| at your option.                                                                                                |
//|                                                                                                                |
//| Unless required by applicable law or agreed to in writing, software distributed                                |
//| under these licenses is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES                                    |
//| OR CONDITIONS OF ANY KIND, either express or implied. See the licenses for details.                            |
//| ============================================================================================================== |

#include <base.h>

static const cstr errno_name_list[] = {
    [EPERM]           = "EPERM",
    [ENOENT]          = "ENOENT",
    [ESRCH]           = "ESRCH",
    [EINTR]           = "EINTR",
    [EIO]             = "EIO",
    [ENXIO]           = "ENXIO",
    [E2BIG]           = "E2BIG",
    [ENOEXEC]         = "ENOEXEC",
    [EBADF]           = "EBADF",
    [ECHILD]          = "ECHILD",
    [EAGAIN]          = "EAGAIN",
    [ENOMEM]          = "ENOMEM",
    [EACCES]          = "EACCES",
    [EFAULT]          = "EFAULT",
    [ENOTBLK]         = "ENOTBLK",
    [EBUSY]           = "EBUSY",
    [EEXIST]          = "EEXIST",
    [EXDEV]           = "EXDEV",
    [ENODEV]          = "ENODEV",
    [ENOTDIR]         = "ENOTDIR",
    [EISDIR]          = "EISDIR",
    [EINVAL]          = "EINVAL",
    [ENFILE]          = "ENFILE",
    [EMFILE]          = "EMFILE",
    [ENOTTY]          = "ENOTTY",
    [ETXTBSY]         = "ETXTBSY",
    [EFBIG]           = "EFBIG",
    [ENOSPC]          = "ENOSPC",
    [ESPIPE]          = "ESPIPE",
    [EROFS]           = "EROFS",
    [EMLINK]          = "EMLINK",
    [EPIPE]           = "EPIPE",
    [EDOM]            = "EDOM",
    [ERANGE]          = "ERANGE",
    [EDEADLK]         = "EDEADLK",
    [ENAMETOOLONG]    = "ENAMETOOLONG",
    [ENOLCK]          = "ENOLCK",
    [ENOSYS]          = "ENOSYS",
    [ENOTEMPTY]       = "ENOTEMPTY",
    [ELOOP]           = "ELOOP",
    [ENOMSG]          = "ENOMSG",
    [EIDRM]           = "EIDRM",
    [ECHRNG]          = "ECHRNG",
    [EL2NSYNC]        = "EL2NSYNC",
    [EL3HLT]          = "EL3HLT",
    [EL3RST]          = "EL3RST",
    [ELNRNG]          = "ELNRNG",
    [EUNATCH]         = "EUNATCH",
    [ENOCSI]          = "ENOCSI",
    [EL2HLT]          = "EL2HLT",
    [EBADE]           = "EBADE",
    [EBADR]           = "EBADR",
    [EXFULL]          = "EXFULL",
    [ENOANO]          = "ENOANO",
    [EBADRQC]         = "EBADRQC",
    [EBADSLT]         = "EBADSLT",
    [EBFONT]          = "EBFONT",
    [ENOSTR]          = "ENOSTR",
    [ENODATA]         = "ENODATA",
    [ETIME]           = "ETIME",
    [ENOSR]           = "ENOSR",
    [ENONET]          = "ENONET",
    [ENOPKG]          = "ENOPKG",
    [EREMOTE]         = "EREMOTE",
    [ENOLINK]         = "ENOLINK",
    [EADV]            = "EADV",
    [ESRMNT]          = "ESRMNT",
    [ECOMM]           = "ECOMM",
    [EPROTO]          = "EPROTO",
    [EMULTIHOP]       = "EMULTIHOP",
    [EDOTDOT]         = "EDOTDOT",
    [EBADMSG]         = "EBADMSG",
    [EOVERFLOW]       = "EOVERFLOW",
    [ENOTUNIQ]        = "ENOTUNIQ",
    [EBADFD]          = "EBADFD",
    [EREMCHG]         = "EREMCHG",
    [ELIBACC]         = "ELIBACC",
    [ELIBBAD]         = "ELIBBAD",
    [ELIBSCN]         = "ELIBSCN",
    [ELIBMAX]         = "ELIBMAX",
    [ELIBEXEC]        = "ELIBEXEC",
    [EILSEQ]          = "EILSEQ",
    [ERESTART]        = "ERESTART",
    [ESTRPIPE]        = "ESTRPIPE",
    [EUSERS]          = "EUSERS",
    [ENOTSOCK]        = "ENOTSOCK",
    [EDESTADDRREQ]    = "EDESTADDRREQ",
    [EMSGSIZE]        = "EMSGSIZE",
    [EPROTOTYPE]      = "EPROTOTYPE",
    [ENOPROTOOPT]     = "ENOPROTOOPT",
    [EPROTONOSUPPORT] = "EPROTONOSUPPORT",
    [ESOCKTNOSUPPORT] = "ESOCKTNOSUPPORT",
    [EOPNOTSUPP]      = "EOPNOTSUPP",
    [EPFNOSUPPORT]    = "EPFNOSUPPORT",
    [EAFNOSUPPORT]    = "EAFNOSUPPORT",
    [EADDRINUSE]      = "EADDRINUSE",
    [EADDRNOTAVAIL]   = "EADDRNOTAVAIL",
    [ENETDOWN]        = "ENETDOWN",
    [ENETUNREACH]     = "ENETUNREACH",
    [ENETRESET]       = "ENETRESET",
    [ECONNABORTED]    = "ECONNABORTED",
    [ECONNRESET]      = "ECONNRESET",
    [ENOBUFS]         = "ENOBUFS",
    [EISCONN]         = "EISCONN",
    [ENOTCONN]        = "ENOTCONN",
    [ESHUTDOWN]       = "ESHUTDOWN",
    [ETOOMANYREFS]    = "ETOOMANYREFS",
    [ETIMEDOUT]       = "ETIMEDOUT",
    [ECONNREFUSED]    = "ECONNREFUSED",
    [EHOSTDOWN]       = "EHOSTDOWN",
    [EHOSTUNREACH]    = "EHOSTUNREACH",
    [EALREADY]        = "EALREADY",
    [EINPROGRESS]     = "EINPROGRESS",
    [ESTALE]          = "ESTALE",
    [EUCLEAN]         = "EUCLEAN",
    [ENOTNAM]         = "ENOTNAM",
    [ENAVAIL]         = "ENAVAIL",
    [EISNAM]          = "EISNAM",
    [EREMOTEIO]       = "EREMOTEIO",
    [EDQUOT]          = "EDQUOT",
    [ENOMEDIUM]       = "ENOMEDIUM",
    [EMEDIUMTYPE]     = "EMEDIUMTYPE",
    [ECANCELED]       = "ECANCELED",
    [ENOKEY]          = "ENOKEY",
    [EKEYEXPIRED]     = "EKEYEXPIRED",
    [EKEYREVOKED]     = "EKEYREVOKED",
    [EKEYREJECTED]    = "EKEYREJECTED",
    [EOWNERDEAD]      = "EOWNERDEAD",
    [ENOTRECOVERABLE] = "ENOTRECOVERABLE",
    [ERFKILL]         = "ERFKILL",
    [EHWPOISON]       = "EHWPOISON",
};

static const cstr errno_desc_list[] = {
    [EPERM]           = "Operation not permitted",
    [ENOENT]          = "No such file or directory",
    [ESRCH]           = "No such process",
    [EINTR]           = "Interrupted system call",
    [EIO]             = "I/O error",
    [ENXIO]           = "No such device or address",
    [E2BIG]           = "Argument list too long",
    [ENOEXEC]         = "Exec format error",
    [EBADF]           = "Bad file number",
    [ECHILD]          = "No child processes",
    [EAGAIN]          = "Try again",
    [ENOMEM]          = "Out of memory",
    [EACCES]          = "Permission denied",
    [EFAULT]          = "Bad address",
    [ENOTBLK]         = "Block device required",
    [EBUSY]           = "Device or resource busy",
    [EEXIST]          = "File exists",
    [EXDEV]           = "Cross-device link",
    [ENODEV]          = "No such device",
    [ENOTDIR]         = "Not a directory",
    [EISDIR]          = "Is a directory",
    [EINVAL]          = "Invalid argument",
    [ENFILE]          = "File table overflow",
    [EMFILE]          = "Too many open files",
    [ENOTTY]          = "Not a typewriter",
    [ETXTBSY]         = "Text file busy",
    [EFBIG]           = "File too large",
    [ENOSPC]          = "No space left on device",
    [ESPIPE]          = "Illegal seek",
    [EROFS]           = "Read-only file system",
    [EMLINK]          = "Too many links",
    [EPIPE]           = "Broken pipe",
    [EDOM]            = "Math argument out of domain of func",
    [ERANGE]          = "Math result not representable",
    [EDEADLK]         = "Resource deadlock would occur",
    [ENAMETOOLONG]    = "File name too long",
    [ENOLCK]          = "No record locks available",
    [ENOSYS]          = "Invalid system call number",
    [ENOTEMPTY]       = "Directory not empty",
    [ELOOP]           = "Too many symbolic links encountered",
    [ENOMSG]          = "No message of desired type",
    [EIDRM]           = "Identifier removed",
    [ECHRNG]          = "Channel number out of range",
    [EL2NSYNC]        = "Level 2 not synchronized",
    [EL3HLT]          = "Level 3 halted",
    [EL3RST]          = "Level 3 reset",
    [ELNRNG]          = "Link number out of range",
    [EUNATCH]         = "Protocol driver not attached",
    [ENOCSI]          = "No CSI structure available",
    [EL2HLT]          = "Level 2 halted",
    [EBADE]           = "Invalid exchange",
    [EBADR]           = "Invalid request descriptor",
    [EXFULL]          = "Exchange full",
    [ENOANO]          = "No anode",
    [EBADRQC]         = "Invalid request code",
    [EBADSLT]         = "Invalid slot",
    [EBFONT]          = "Bad font file format",
    [ENOSTR]          = "Device not a stream",
    [ENODATA]         = "No data available",
    [ETIME]           = "Timer expired",
    [ENOSR]           = "Out of streams resources",
    [ENONET]          = "Machine is not on the network",
    [ENOPKG]          = "Package not installed",
    [EREMOTE]         = "Object is remote",
    [ENOLINK]         = "Link has been severed",
    [EADV]            = "Advertise error",
    [ESRMNT]          = "Srmount error",
    [ECOMM]           = "Communication error on send",
    [EPROTO]          = "Protocol error",
    [EMULTIHOP]       = "Multihop attempted",
    [EDOTDOT]         = "RFS specific error",
    [EBADMSG]         = "Not a data message",
    [EOVERFLOW]       = "Value too large for defined data type",
    [ENOTUNIQ]        = "Name not unique on network",
    [EBADFD]          = "File descriptor in bad state",
    [EREMCHG]         = "Remote address changed",
    [ELIBACC]         = "Can not access a needed shared library",
    [ELIBBAD]         = "Accessing a corrupted shared library",
    [ELIBSCN]         = ".lib section in a.out corrupted",
    [ELIBMAX]         = "Attempting to link in too many shared libraries",
    [ELIBEXEC]        = "Cannot exec a shared library directly",
    [EILSEQ]          = "Illegal byte sequence",
    [ERESTART]        = "Interrupted system call should be restarted",
    [ESTRPIPE]        = "Streams pipe error",
    [EUSERS]          = "Too many users",
    [ENOTSOCK]        = "Socket operation on non-socket",
    [EDESTADDRREQ]    = "Destination address required",
    [EMSGSIZE]        = "Message too long",
    [EPROTOTYPE]      = "Protocol wrong type for socket",
    [ENOPROTOOPT]     = "Protocol not available",
    [EPROTONOSUPPORT] = "Protocol not supported",
    [ESOCKTNOSUPPORT] = "Socket type not supported",
    [EOPNOTSUPP]      = "Operation not supported on transport endpoint",
    [EPFNOSUPPORT]    = "Protocol family not supported",
    [EAFNOSUPPORT]    = "Address family not supported by protocol",
    [EADDRINUSE]      = "Address already in use",
    [EADDRNOTAVAIL]   = "Cannot assign requested address",
    [ENETDOWN]        = "Network is down",
    [ENETUNREACH]     = "Network is unreachable",
    [ENETRESET]       = "Network dropped connection because of reset",
    [ECONNABORTED]    = "Software caused connection abort",
    [ECONNRESET]      = "Connection reset by peer",
    [ENOBUFS]         = "No buffer space available",
    [EISCONN]         = "Transport endpoint is already connected",
    [ENOTCONN]        = "Transport endpoint is not connected",
    [ESHUTDOWN]       = "Cannot send after transport endpoint shutdown",
    [ETOOMANYREFS]    = "Too many references: cannot splice",
    [ETIMEDOUT]       = "Connection timed out",
    [ECONNREFUSED]    = "Connection refused",
    [EHOSTDOWN]       = "Host is down",
    [EHOSTUNREACH]    = "No route to host",
    [EALREADY]        = "Operation already in progress",
    [EINPROGRESS]     = "Operation now in progress",
    [ESTALE]          = "Stale file handle",
    [EUCLEAN]         = "Structure needs cleaning",
    [ENOTNAM]         = "Not a XENIX named type file",
    [ENAVAIL]         = "No XENIX semaphores available",
    [EISNAM]          = "Is a named type file",
    [EREMOTEIO]       = "Remote I/O error",
    [EDQUOT]          = "Quota exceeded",
    [ENOMEDIUM]       = "No medium found",
    [EMEDIUMTYPE]     = "Wrong medium type",
    [ECANCELED]       = "Operation Canceled",
    [ENOKEY]          = "Required key not available",
    [EKEYEXPIRED]     = "Key has expired",
    [EKEYREVOKED]     = "Key has been revoked",
    [EKEYREJECTED]    = "Key was rejected by service",
    [EOWNERDEAD]      = "Owner died",
    [ENOTRECOVERABLE] = "State not recoverable",
    [ERFKILL]         = "Operation not possible due to RF-kill",
    [EHWPOISON]       = "Memory page has hardware error",
};

static const cstr errno_name_unknown = "UNKNOWN";
static const cstr errno_desc_unknown = "Unknown error";

dlexport WEAK char *strerror(int e) noexcept {
  static char buf[64];
  return strcpy(buf, strerrordesc_np(e));
}

#if defined __USE_XOPEN2K && !defined __USE_GNU
dlexport WEAK int strerror_r(int e, char *buf, size_t n) noexcept {
  if (e < 0 || e > ERRNO_MAX) {
    strncpy(buf, errno_desc_unknown, n);
    return -1;
  }
  strncpy(buf, errno_list[e] ?: errno_desc_unknown, n);
  return 0;
}
#else
dlexport WEAK char *strerror_r(int e, char *buf, size_t n) noexcept {
  return strncpy(buf, strerrordesc_np(e), n);
}
#endif

dlexport WEAK cstr strerrordesc_np(int e) noexcept {
  if (e < 0 || e > ERRNO_MAX) return errno_desc_unknown;
  return errno_desc_list[e] ?: errno_desc_unknown;
}

dlexport WEAK cstr strerrorname_np(int e) noexcept {
  if (e < 0 || e > ERRNO_MAX) return errno_name_unknown;
  return errno_name_list[e] ?: errno_name_unknown;
}
