// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "pixel/define.hpp"
#include "pixel/init.hpp"
#include "pixel/mix.hpp"
#include "pixel/op.hpp"
#include "pixel/pixel.hpp"
#include "pixel/using.hpp"
#endif // __cplusplus
