// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "points/col.hpp"
#include "points/line.hpp"
#include "points/rect.hpp"
#include "points/row.hpp"
#include "points/triangle.hpp"
#endif // __cplusplus
