// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "texture/get-set.hpp"
#include "texture/paste.hpp"
#include "texture/texture.hpp"
#include "texture/trans.hpp"
#endif // __cplusplus
