// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "base/00-include.h"
#include "base/arg.h"
#include "base/color.h"
#include "base/errno.h"
#include "base/error.h"
#include "base/time.h"
#include "base/crypto/hash.h"
#include "base/math/base.h"
#include "base/math/bits.h"
#include "base/math/exp-log.h"
#include "base/math/float.h"
#include "base/math/math.h"
#include "base/math/sin.h"
#include "base/math/sqrt.h"
#include "base/math/complex/base.h"
#include "base/math/complex/complex.h"
#include "base/stdio/print.h"
#include "base/stdlib/alloc.h"
#include "base/stdlib/atox.h"
#include "base/stdlib/lib.h"
#include "base/stdlib/rand.h"
#include "base/stdlib/xtoa.h"
#include "base/string/alloc.h"
#include "base/string/mem.h"
#include "base/string/path.h"
#include "base/string/str.h"
#include "base/string/charset.h"
#include "base/thread/rwlock.h"
#include "base/thread/spin.h"
#ifdef __cplusplus
}
#endif // __cplusplus
