// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "base/00-include.hpp"
#include "base/error.hpp"
#include "base/exch.hpp"
#include "base/rc.hpp"
#include "base/time.hpp"
#include "base/unit.hpp"
#include "base/math/base.hpp"
#include "base/math/bits.hpp"
#include "base/math/exp-log.hpp"
#include "base/math/math.hpp"
#include "base/math/min-max.hpp"
#include "base/math/sin.hpp"
#include "base/math/sqrt.hpp"
#include "base/math/sum.hpp"
#include "base/thread/spin.hpp"
#include "base/math/complex/base.hpp"
#include "base/math/complex/complex.hpp"
#endif // __cplusplus
