// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "define/plos-definitions.h"
#include "define/config/alloc.h"
#include "define/config/check.h"
#include "define/config/data-structure.h"
#include "define/config/log.h"
#include "define/config/string-format.h"
#include "define/config/undef.h"
#include "define/config/plos.h"
#include "define/config/plui.h"
#include "define/define/00-include.h"
#include "define/define/assert.h"
#include "define/define/logging.h"
#include "define/define/magic.h"
#include "define/define/mem.h"
#include "define/define/rc.h"
#include "define/define/va.h"
#include "define/define/new.h"
#include "define/define/base.h"
#include "define/define/attribute.h"
#include "define/define/int.h"
#include "define/type/00-include.h"
#include "define/type/atom-func.h"
#include "define/type/atom-lockfree.h"
#include "define/type/atom-type.h"
#include "define/type/atom.h"
#include "define/type/base.h"
#include "define/type/bool.h"
#include "define/type/char.h"
#include "define/type/complex.h"
#include "define/type/ex.h"
#include "define/type/func.h"
#include "define/type/int.h"
#include "define/type/limit.h"
#include "define/type/vector.h"
#include "define/type/bitint.h"
#include "define/type/complex-bitint.h"
#include "define/type/addr.h"
#ifdef __cplusplus
}
#endif // __cplusplus
