// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "plds/base/00-include.hpp"
#include "plds/client/00-include.hpp"
#include "plds/server/00-include.hpp"
#include "plds/server/api.hpp"
#include "plds/server/var.hpp"
#endif // __cplusplus
