// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "plui/element.hpp"
#include "plui/event.hpp"
#include "plui/pos.hpp"
#include "plui/wnd.hpp"
#endif // __cplusplus
