// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "misc/00-include.h"
#include "misc/color.h"
#include "misc/file.h"
#include "misc/crypto/codec.h"
#include "misc/crypto/hash.h"
#include "misc/math/fft.h"
#include "misc/math/mdct.h"
#include "misc/stdio/print.h"
#ifdef __cplusplus
}
#endif // __cplusplus
#ifdef __cplusplus
#include "misc/00-include.hpp"
#include "misc/string.hpp"
#include "misc/math/fft.hpp"
#include "misc/math/gaussian-blur.hpp"
#endif // __cplusplus
