// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "pci/class.h"
#include "pci/enum.h"
#ifdef __cplusplus
}
#endif // __cplusplus
