// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "amd64/asm.h"
#include "amd64/cpuid.h"
#include "amd64/cr.h"
#include "amd64/flags.h"
#include "amd64/io.h"
#include "amd64/mem.h"
#include "amd64/msr.h"
#include "amd64/reg.h"
#include "amd64/syscall.h"
#include "amd64/alias.h"
#ifdef __cplusplus
}
#endif // __cplusplus
