// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "kernel/cpu.h"
#include "kernel/thread.h"
#include "kernel/page.h"
#include "kernel/kmman.h"
#include "kernel/typedefs.h"
#ifdef __cplusplus
}
#endif // __cplusplus
