#!/usr/bin/sh

clean_file() {
  perl -0777 -pe 's{(?://[^\n]*|/\*.*?\*/)}{}gs' -i "$1" # 去除注释
  sed -i 's/^[[:space:]]*//; s/[[:space:]]*$//' "$1"     # 去除行首和行尾的空格
  perl -0777 -pe 's/\\\n/ /g' -i "$1"                    # 将行尾的反斜杠及换行替换为单个空格
  sed -i 's/ \{2,\}/ /g' "$1"                            # 将多个空格替换为一个空格
  sed -i '/^[[:space:]]*$/d' "$1"                        # 删除空行

  sed -i '/^#pragma once/d' "$1"
  sed -i '/^#pragma GCC system_header/d' "$1"
}

write_file() {
  sed -i '1i\
//| ============================================================================================================== |\
//| This file is automatically generated, please do not modify it.                                                 |\
//| ============================================================================================================== |\
//| Copyright (c) 2025 plos-clan                                                                                   |\
//|                                                                                                                |\
//| This file is part of the Pico Logic OS.                                                                        |\
//|                                                                                                                |\
//| Licensed under either of:                                                                                      |\
//| - Apache License, Version 2.0 (see LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0)               |\
//| - MIT License (see LICENSE-MIT or https://opensource.org/licenses/MIT)                                         |\
//| at your option.                                                                                                |\
//|                                                                                                                |\
//| Unless required by applicable law or agreed to in writing, software distributed                                |\
//| under these licenses is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES                                    |\
//| OR CONDITIONS OF ANY KIND, either express or implied. See the licenses for details.                            |\
//| ============================================================================================================== |\
#pragma once\
#pragma GCC system_header' "$1"
}

mkdir -p ./generated

# * ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== * #

./amalgamate -s -i ./include -d AMALGAMATE=1 ./include/define.h ./generated/define.h

clean_file ./generated/define.h

write_file ./generated/define.h

# * ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== * #

./amalgamate -i ./include -d AMALGAMATE=1 ./include/asm.h ./generated/asm.h

clean_file ./generated/asm.h

sed -i '/^#[[:space:]]*include/d' ./generated/asm.h

write_file ./generated/asm.h

# * ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== * #

./amalgamate -i ./include -d AMALGAMATE=1 ./include/base.h ./generated/base.h

clean_file ./generated/base.h

sed -i '/^#[[:space:]]*include/d' ./generated/base.h

write_file ./generated/base.h

# * ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== * #
