// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "k1/gpio.h"
#include "k1/lcd.h"
#include "k1/mfpr.h"
#include "k1/pwm.h"
#include "k1/spi.h"
#include "k1/timer.h"
#include "k1/uart.h"
#include "k1/watchdog.h"
#ifdef __cplusplus
}
#endif // __cplusplus
