// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "../algorithm/base.h"
#include "../algorithm/bm.h"
#include "../algorithm/kmp.h"
#ifdef __cplusplus
}
#endif // __cplusplus
