// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
#include "../data-structure/base.hpp"
#include "../data-structure/ordered-set/list.hpp"
#include "../data-structure/ordered-set/queue.hpp"
#include "../data-structure/ordered-set/bitmap.hpp"
#include "../data-structure/ordered-set/array.hpp"
#include "../data-structure/sorted-map/rbtree.hpp"
#endif // __cplusplus
