// This file is automatically generated, please do not modify it.
// %% generated %%
// %% include-generated %%
#pragma once
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#include "pthread/thread.h"
#include "pthread/mutex.h"
#include "pthread/cond.h"
#include "pthread/rwlock.h"
#ifdef __cplusplus
}
#endif // __cplusplus
